# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:stable
  amd64: ghcr.io/hassio-addons/debian-base/amd64:stable
  #armhf: ghcr.io/hassio-addons/debian-base/armhf:stable
  #armv7: ghcr.io/hassio-addons/debian-base/armv7:stable
  #i386: ghcr.io/hassio-addons/debian-base/i386:stable
labels:
  org.opencontainers.image.title: "Home Assistant Addon: Minecraft Server Bedrock"
  org.opencontainers.image.description: "This addon runs a minecraft server bedrock edition. It can be fully configured in the UI."
  org.opencontainers.image.source: "https://github.com/UnknownEnergy/addons-example"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
